name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: ./backend
      run: npm install

    - name: Set environment variables
      run: |
        echo "EDAMAM_APP_KEY=${{ secrets.EDAMAM_APP_KEY }}" >> $GITHUB_ENV
        echo "EDAMAM_APP_ID=${{ secrets.EDAMAM_APP_ID }}" >> $GITHUB_ENV
        echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
        echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
        echo "HTTPS_KEY_PATH=${{ secrets.HTTPS_KEY_PATH }}" >> $GITHUB_ENV
        echo "HTTPS_CERT_PATH=${{ secrets.HTTPS_CERT_PATH }}" >> $GITHUB_ENV

    - name: Run tests
      working-directory: ./backend
      run: npm test

    - name: Build Docker image
      run: docker build -t firatss/recipeapp-backend:latest ./backend

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push firatss/recipeapp-backend:latest
