name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: ./backend
      run: npm install

    - name: Run tests
      working-directory: ./backend
      run: npm test
      env:
          EDAMAM_APP_KEY: ${{ secrets.EDAMAM_APP_KEY }}
          EDAMAM_APP_ID: ${{ secrets.EDAMAM_APP_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
